spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#1
#  datasource:
#    url: jdbc:postgresql://localhost:5435/attendance
#    username: admin
#    password: pass_admin

#2
#  datasource:
#    url: jdbc:postgresql://localhost:5436/attendance2
#    username: admin2
#    password: pass_admin2

  #3
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-wild-dew-a2b41y8w-pooler.eu-central-1.aws.neon.tech:5432/verceldb?sslmode=require
    username: default
    password: Ky6pc1uYFlMg

  mvc:
    static-path-pattern: /static/**


server:
  port: 80